# This file was generated by an experimental feature called 'Gather'.
#
#     The intent is that it contains only the code required to produce
#     the same results as the cell originally selected for gathering.
#     Please note that the Python analysis is quite conservative, so if
#     it is unsure whether a line of code is necessary for execution, it
#     will err on the side of including it.
#
# Please let us know if you are satisfied with what was gathered here:
# https://aka.ms/gathersurvey

# %%
query_string = "mark wiens"


def add_urls_list(search_results, verbose, source, **kwargs):
    """
    Fake function that mocks add_urls_mongo
    rtype: list
    """
    return list(set(search_results))

# %%
yt = YouTubeDataAPI(os.environ.get('YOUTUBE_API_KEY'))
res = yt.search(query_string, max_results=50)
df = pd.DataFrame(res)

# %%
df.head()

# %%
df.describe()

# %%
df["channel_title"].unique()


# %%
df2, added, urls_to_add = add_urls_mongo_fom_recommended_videos('Fue_oeI45CA', destination_func=add_urls_list, return_df=True)

# %%
df2.head()
